# Generated by Django 3.1.14 on 2023-12-11 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('francoralite_api', '0009_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name_plural': 'keywords',
                'db_table': 'api_keyword',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='francoralite_api.item', verbose_name='Item')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='francoralite_api.keyword', verbose_name='Keyword')),
            ],
            options={
                'verbose_name_plural': 'item_keywords',
                'db_table': 'api_item_keyword',
                'ordering': [],
                'unique_together': {('item', 'keyword')},
            },
        ),
    ]
