# Generated by Django 3.1.14 on 2024-01-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('francoralite_api', '0010_itemkeyword_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefLaforte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Laforte',
                'verbose_name_plural': 'Laforte',
                'db_table': 'api_ref_laforte',
            },
        ),
        migrations.CreateModel(
            name='ItemLaforte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='francoralite_api.item', verbose_name='item')),
                ('laforte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='francoralite_api.reflaforte', verbose_name='Laforte')),
            ],
            options={
                'verbose_name_plural': 'item_lafortes',
                'db_table': 'api_item_laforte',
                'ordering': [],
                'unique_together': {('item', 'laforte')},
            },
        ),
    ]
