# Generated by Django 3.1.14 on 2024-01-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francoralite_api', '0011_itemlaforte_laforte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reflaforte',
            old_name='name',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='reflaforte',
            old_name='description',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='reflaforte',
            name='number',
            field=models.CharField(max_length=40, unique=True, verbose_name='numérotation'),
        ),
        migrations.AlterField(
            model_name='reflaforte',
            name='name',
            field=models.CharField(default='', max_length=500, verbose_name='nom'),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='reflaforte',
            options={'ordering': ['number'], 'verbose_name': 'Laforte', 'verbose_name_plural': 'Laforte'},
        ),
        migrations.AlterField(
            model_name='skoscollection',
            name='number',
            field=models.CharField(default='', max_length=40, verbose_name='numérotation'),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='skoscollection',
            options={'ordering': ['number'], 'verbose_name_plural': 'skos_collections'},
        ),
        migrations.AlterField(
            model_name='skosconcept',
            name='number',
            field=models.CharField(max_length=40, verbose_name='numérotation'),
        ),
        migrations.AlterModelOptions(
            name='skosconcept',
            options={'ordering': ['number'], 'verbose_name_plural': 'skos_concepts'},
        ),
    ]
