# Generated by Django 3.1.14 on 2024-01-24 14:59

from django.db import migrations, models
import django.db.models.deletion


def create_civilities(apps, schema_editor):
    AuthorityCivility = apps.get_model('francoralite_api', 'AuthorityCivility')
    Authority = apps.get_model('francoralite_api', 'Authority')
    Civility = apps.get_model('francoralite_api', 'Civility')

    civilities_ids = {}

    qs = Authority.objects.values_list('civility', flat=True)
    qs = qs.exclude(civility=None).exclude(civility='')
    qs = qs.order_by('civility').distinct()
    for name in qs:
        civilities_ids[name] = Civility.objects.get_or_create(name=name)[0].id

    qs = Authority.objects.values_list('id', 'civility')
    qs = qs.exclude(civility=None).exclude(civility='')
    for authority_id, civility_name in qs:
        AuthorityCivility.objects.create(
            authority_id=authority_id,
            civility_id=civilities_ids[civility_name],
        )


def reverse_civilities(apps, schema_editor):
    AuthorityCivility = apps.get_model('francoralite_api', 'AuthorityCivility')
    Authority = apps.get_model('francoralite_api', 'Authority')

    qs = AuthorityCivility.objects.values_list('authority_id', 'civility__name')
    for authority_id, civility_name in qs:
        Authority.objects.filter(id=authority_id).update(civility=civility_name)


class Migration(migrations.Migration):

    dependencies = [
        ('francoralite_api', '0012_alter_coirault_laforte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Civility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'civilité',
                'verbose_name_plural': 'civilités',
                'db_table': 'api_civility',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuthorityCivility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='francoralite_api.authority', verbose_name='authority')),
                ('civility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='francoralite_api.civility', verbose_name='civility')),
            ],
            options={
                'verbose_name': 'civility of an authority',
                'verbose_name_plural': 'civilities of authorities',
                'db_table': 'authority_civility',
                'ordering': [],
                'unique_together': {('authority', 'civility')},
            },
        ),
        migrations.RunPython(
            code=create_civilities,
            reverse_code=reverse_civilities,
            atomic=True,
        ),
        migrations.RemoveField(
            model_name='authority',
            name='civility',
        ),
    ]
