
language: python
python:
  - "3.7"

sudo: required

services:
  - docker

# Install Francoralite
install:
  - git clone https://github.com/lluc/telemeta-integration.git
  - git submodule update --recursive --init
  - docker-compose pull
  - docker-compose build


before_script:
  - docker network create services

script:
  - docker-compose up -d
  - sleep 30
  - ./scripts/load_keycloak_data.sh
  - docker-compose exec app bash -c 'pip install --no-cache-dir .[tests]'
  - docker-compose exec app bash -c 'py.test'
after_script:
  - docker-compose stop
  - docker-compose down


after_failure:
  - docker-compose logs
