env:
  - DJANGO_VERSION=1.8

language: python
python:
  - "2.7"

sudo: required

services:
  - docker

# Install Telemeta
install:
  - docker-compose pull
  - docker-compose build

script:
  - docker-compose up -d
  - sleep 60
after_script:
  - docker-compose stop
  - docker-compose down


after_failure:
  - docker-compose logs
