---

version: '2.1'

services:
  data:
    labels:
      - 'traefik.frontend.rule=Host:data.francoralite.localhost'

  db:
    labels:
      - 'traefik.frontend.rule=Host:db.francoralite.localhost'

  broker:
    labels:
      - 'traefik.frontend.rule=Host:broker.francoralite.localhost'

  search:
    labels:
      - 'traefik.frontend.rule=Host:search.francoralite.localhost'

  app:
    labels:
      - 'traefik.frontend.rule=Host:app.francoralite.localhost'

  worker:
    labels:
      - 'traefik.frontend.rule=Host:worker.francoralite.localhost'

  nginx:
    labels:
      - 'traefik.frontend.rule=Host:nginx.francoralite.localhost'

  phpmyadmin:
    labels:
      - 'traefik.frontend.rule=Host:phpmyadmin.francoralite.localhost'

  keycloak:
    labels:
      - 'traefik.frontend.rule=Host:keycloak.francoralite.localhost'

  keycloak_db:
    labels:
      - 'traefik.frontend.rule=Host:keycloak-db.francoralite.localhost'

  reverse_proxy:
    image: 'traefik:1.7.11'
    command: '--api --docker --docker.domain=francoralite.localhost'
    networks:
      - 'keycloak'
      - 'services'
    ports:
      - '8080:80'
      - '58080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
