---

# Docker compose to build Telemeta meta project

version: '2.1'

networks:
  telemeta: {}
  services:
    external:
      name: 'services'

services:
  data:
    image: 'debian:jessie'
    networks:
      - 'telemeta'
    volumes:
       - './data/media/:/srv/media'
       - './data/backup/:/srv/backup'
       - './data/static:/srv/static'
       - './data/bower:/srv/bower'
       - './data/log/nginx:/var/log/nginx'
       - './data/log/uwsgi:/var/log/uwsgi'
    command: 'true'

  db:
    image: 'mysql:8.0.2'
    volumes:
      - './telemeta_mshs/apps/Telemeta/scripts/:/srv/scripts'
      - './data/mysql/:/var/lib/mysql'
    networks:
      - 'telemeta'
    volumes_from:
      - 'data'
    env_file:
      - './telemeta_mshs/apps/Telemeta/env/prod.env'
    healthcheck:
      test: ["CMD-SHELL", "mysql -u $${MYSQL_USER} -p$${MYSQL_PASSWORD} -e 'SHOW DATABASES;'"]
      interval: '30s'
      timeout: '2s'
      retries: 3

  broker:
    image: 'redis'
    networks:
      - 'telemeta'

  search:
    image: 'elasticsearch:1'
    networks:
      - 'telemeta'

  app:
    build:
      context: .
    networks:
      - 'services'
      - 'telemeta'
    volumes:
      - './:/srv/app'
      - './scripts:/srv/scripts'
      - './telemeta_mshs/apps/Telemeta/app/enumeration:/srv/app/enumeration'
      - './telemeta_mshs/apps/Telemeta/app/fixtures:/srv/app/fixtures'
      - './telemeta_mshs/settings/base.py:/srv/app/settings.py'
      - './telemeta_mshs/apps/Telemeta/app/settings.py:/srv/app/telemeta_settings.py'
      - './telemeta_mshs/apps/Telemeta/app/worker.py:/srv/app/worker.py'
      - './telemeta_mshs/apps/Telemeta/app/robots.txt:/srv/app/telemeta_mshs/robots.txt'
    volumes_from:
      - 'data'
    env_file:
      - './telemeta_mshs/apps/Telemeta/env/debug.env'
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 8000"]
      interval: '10s'
      timeout: '2s'
      retries: 20
    command: '/bin/bash /srv/scripts/start_api.sh'
    depends_on:
      db:
        condition: 'service_healthy'

  worker:
    build:
      context: .
    networks:
      - 'telemeta'
    volumes_from:
      - 'app'
    env_file:
      - './telemeta_mshs/apps/Telemeta/env/prod.env'
    command: '/bin/bash /srv/scripts/start_worker.sh'
    depends_on:
      app:
        condition: 'service_healthy'

  nginx:
    image: 'nginx'
    networks:
      - 'services'
    ports:
      - '8000:80'
    volumes:
      - './etc/nginx.conf:/etc/nginx/conf.d/default.conf'
    volumes_from:
      - 'data'

  phpmyadmin:
    image: 'nazarpc/phpmyadmin'
    networks:
      - 'services'
      - 'telemeta'
    environment:
      - ABSOLUTE_URI=http://localhost:8000/phpmyadmin/
