---

version: '2.1'

x-logging:
  &default-logging
  driver: 'json-file'
  options:
    max-size: "${LOGGING_MAX_SIZE}"
    max-file: "${LOGGING_MAX_FILE}"

services:
  data:
    labels:
      - 'traefik.frontend.rule=Host:data.francoralite.localhost'

  db:
    labels:
      - 'traefik.frontend.rule=Host:db.francoralite.localhost'

  broker:
    labels:
      - 'traefik.frontend.rule=Host:broker.francoralite.localhost'

  search:
    labels:
      - 'traefik.frontend.rule=Host:search.francoralite.localhost'

  app:
    labels:
      - 'traefik.frontend.rule=Host:app.francoralite.localhost'
      - 'traefik.docker.network=services'

  worker:
    labels:
      - 'traefik.frontend.rule=Host:worker.francoralite.localhost'

  nginx:
    labels:
      - 'traefik.frontend.rule=Host:nginx.francoralite.localhost'
      - 'traefik.docker.network=services'


  phpmyadmin:
    image: "${PHPMYADMIN_IMAGE_NAME}:${PHPMYADMIN_IMAGE_VERSION}"
    restart: 'unless-stopped'
    logging: *default-logging
    environment:
      - ABSOLUTE_URI=http://phpmyadmin.francoralite.localhost:50000/phpmyadmin/
    labels:
      - 'traefik.frontend.rule=Host:phpmyadmin.francoralite.localhost'
      - 'traefik.docker.network=services'
    networks:
      - 'services'
      - 'francoralite'

  keycloak:
    labels:
      - 'traefik.frontend.rule=Host:keycloak.francoralite.localhost'
      - 'traefik.docker.network=services'

  keycloak_db:
    labels:
      - 'traefik.frontend.rule=Host:keycloak-db.francoralite.localhost'

  reverse_proxy:
    image: "${TRAEFIK_IMAGE_NAME}:${TRAEFIK_IMAGE_VERSION}"
    command: '--api --docker --docker.domain=francoralite.localhost'
    restart: 'unless-stopped'
    logging: *default-logging
    networks:
      - 'keycloak'
      - 'services'
    ports:
      - '8080:80'
      - '58080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
