---

# Docker compose to build Telemeta meta project

version: '2.1'

networks:
  keycloak: {}
  francoralite: {}
  services:
    external:
      name: 'services'

services:
  db:
    image: 'mysql:8.0.2'
    volumes:
      - 'francoralite_db:/var/lib/mysql'
    networks:
      - 'francoralite'
    env_file:
      - './francoralite-env/prod.env'
    healthcheck:
      test: ["CMD-SHELL", "mysql -u $${MYSQL_USER} -p$${MYSQL_PASSWORD} -e 'SHOW DATABASES;'"]
      interval: '30s'
      timeout: '2s'
      retries: 3

  app:
    build:
      context: .
    networks:
      - 'services'
      - 'francoralite'
    volumes:
      - './:/srv/app'
      - './etc/keycloak/auth.json:/tmp/authorization_config.json'
      - 'francoralite_app_bower:/srv/bower'
      - 'francoralite_app_media:/srv/media'
      - 'francoralite_app_static:/srv/static'
    env_file:
      - './francoralite-env/prod.env'
      - './francoralite-env/app.env'
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 8000"]
      interval: '10s'
      timeout: '2s'
      retries: 20
    depends_on:
      db:
        condition: 'service_healthy'

  nginx:
    image: 'nginx'
    depends_on:
      - 'app'
      - 'keycloak'
      - 'adminer'
    networks:
      - 'services'
    volumes:
      - './etc/nginx.conf:/etc/nginx/conf.d/default.conf'
      - 'francoralite_app_bower:/srv/bower'
      - 'francoralite_app_media:/srv/media'
      - 'francoralite_app_static:/srv/static'

  adminer:
    image: "${ADMINER_IMAGE}:${ADMINER_VERSION}"
    restart: 'unless-stopped'
    logging:
      driver: 'json-file'
      options:
        max-size: "${LOGGING_MAX_SIZE}"
        max-file: "${LOGGING_MAX_FILE}"
    networks:
      - 'services'
      - 'francoralite'

  keycloak:
    image: "${KEYCLOAK_IMAGE}:${KEYCLOAK_VERSION}"
    restart: 'unless-stopped'
    logging:
      driver: 'json-file'
      options:
        max-size: "${LOGGING_MAX_SIZE}"
        max-file: "${LOGGING_MAX_FILE}"
    env_file:
      - './francoralite-env/keycloak.env'
    networks:
      keycloak:
        aliases:
          - 'keycloak'
      services:
        aliases:
          - 'keycloak'
          - 'keycloak.francoralite.localhost'
    depends_on:
      - 'keycloak_db'

  keycloak_db:
    image: "${POSTGRES_IMAGE}:${POSTGRES_VERSION}"
    restart: 'unless-stopped'
    logging:
      driver: 'json-file'
      options:
        max-size: "${LOGGING_MAX_SIZE}"
        max-file: "${LOGGING_MAX_FILE}"
    env_file:
      - './francoralite-env/keycloak_database.env'
    networks:
      - 'keycloak'
    volumes:
      - 'keycloak_db:/var/lib/postgresql/data'

volumes:
  francoralite_app_bower: {}
  francoralite_app_media: {}
  francoralite_app_static: {}
  francoralite_db: {}
  keycloak_db: {}
