# -*- coding: utf-8 -*-
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Authors: Luc LEGER / Coopérative ARTEFACTS <artefacts.lle@gmail.com>

from django.conf.urls import url, include

from .views import (
    home as home_integration,
    institution, institution_add, institution_delete, institution_detail,
    institution_edit,
    personne, personne_add, personne_detail, personne_edit, personne_delete,
    personne_collector, personne_informer, personne_author, personne_composer,
    personne_editor,
    location, location_add, location_detail, location_edit, location_delete,
    location_gis, location_gis_add, location_gis_detail, location_gis_edit,
    location_gis_delete,
    location_gis_collection,
    fond, fond_add, fond_detail, fond_edit, fond_delete,
    mission, mission_add, mission_detail, mission_edit, mission_delete,
    collection, collection_add, collection_detail, collection_edit,
    collection_delete,
    item, item_add, item_detail, item_edit,
    item_delete,
    search as search_integration,
    search_advanced,
)

from .views.enum import (
    instrument, instrument_edit, instrument_delete, instrument_detail,
    instrument_add,
    domain_song, domain_song_edit, domain_song_delete, domain_song_detail,
    domain_song_add,
    domain_music, domain_music_edit, domain_music_delete, domain_music_detail,
    domain_music_add,
    domain_tale, domain_tale_edit, domain_tale_delete, domain_tale_detail,
    domain_tale_add,
    domain_vocal, domain_vocal_edit, domain_vocal_delete, domain_vocal_detail,
    domain_vocal_add,
    dance, dance_edit, dance_delete, dance_detail,
    dance_add,
    emit_vox, emit_vox_edit, emit_vox_delete, emit_vox_detail,
    emit_vox_add,
    language, language_edit, language_delete, language_detail, language_add,
    musical_organization, musical_organization_edit,
    musical_organization_delete, musical_organization_detail,
    musical_organization_add,
    hornbostelsachs, hornbostelsachs_edit, hornbostelsachs_delete,
    hornbostelsachs_detail, hornbostelsachs_add,
    musical_group, musical_group_edit,
    musical_group_delete, musical_group_detail,
    musical_group_add,
    thematic, thematic_edit, thematic_delete, thematic_detail,
    thematic_add,
    coirault_detail,
    usefulness, usefulness_edit, usefulness_delete, usefulness_detail,
    usefulness_add,
    coupe, coupe_edit, coupe_delete, coupe_detail,
    coupe_add,
    legal_rights, legal_rights_edit, legal_rights_delete, legal_rights_detail,
    legal_rights_add,
    mediatype, mediatype_edit, mediatype_delete, mediatype_detail,
    mediatype_add,
    metadata_author, metadata_author_edit, metadata_author_delete,
    metadata_author_detail, metadata_author_add,
    publisher, publisher_edit, publisher_delete, publisher_detail,
    publisher_add,
    recording_context, recording_context_edit, recording_context_delete,
    recording_context_detail, recording_context_add,
)


urlpatterns = [
    url(r'^$', home_integration.HomePageView.as_view(), name="home"),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^search/', search_integration.SearchView.as_view(),
        name="search-simple"),
    url(r'^search_advanced/', search_advanced.SearchAdvancedView.as_view(),
        name="search-advanced"),

    # Institutions
    url(r'^institution$', institution.InstitutionView.as_view(),
        name="institution"),
    url(r'^institution/(?P<id>[0-9]+)$',
        institution_detail.InstitutionDetail.as_view(),
        name='institution-detail'),
    url(r'^institution/add$',
        institution_add.InstitutionAdd.as_view(),
        name='institution-add'),
    url(r'^institution/edit(?P<id>[0-9]+)$',
        institution_edit.InstitutionEdit.as_view(),
        name='institution-edit'),
    url(r'^institution/delete(?P<id>[0-9]+)$',
        institution_delete.InstitutionDelete.as_view(),
        name='institution-delete'),

    # Authority  (Personnes)
    url(r'^authority$', personne.PersonneView.as_view(),
        name="personne"),
    url(r'^authority/add$',
        personne_add.PersonneAdd.as_view(),
        name='personne-add'),
    url(r'^authority/(?P<id>[0-9]+)$',
        personne_detail.PersonneDetail.as_view(),
        name='personne-detail'),
    url(r'^authority/edit/(?P<id>[0-9]+)$',
        personne_edit.PersonneEdit.as_view(),
        name='personne-edit'),
    url(r'^authority/delete/(?P<id>[0-9]+)$',
        personne_delete.PersonneDelete.as_view(),
        name='personne-delete'),
    url(r'^authority_collector$',
        personne_collector.PersonneCollectorView.as_view(),
        name="personne-collector"),
    url(r'^authority_informer$',
        personne_informer.PersonneInformerView.as_view(),
        name="personne-informer"),
    url(r'^authority_author$',
        personne_author.PersonneAuthorView.as_view(),
        name="personne-author"),
    url(r'^authority_composer$',
        personne_composer.PersonneComposerView.as_view(),
        name="personne-composer"),
    url(r'^authority_editor$',
        personne_editor.PersonneEditorView.as_view(),
        name="personne-editor"),


    # Location ( Lieux)
    url(r'^location$', location.LocationView.as_view(),
        name="location"),
    url(r'^location/add$',
        location_add.LocationAdd.as_view(),
        name='location-add'),
    url(r'^location/(?P<id>[0-9]+)$',
        location_detail.LocationDetail.as_view(),
        name='location-detail'),
    url(r'^location/edit/(?P<id>[0-9]+)$',
        location_edit.LocationEdit.as_view(),
        name='location-edit'),
    url(r'^location/delete/(?P<id>[0-9]+)$',
        location_delete.LocationDelete.as_view(),
        name='location-delete'),

    # Location GIS ( Lieux)
    url(r'^location_gis/$', location_gis.LocationView.as_view(),
        name="location_gis"),
    url(r'^location_gis/add$',
        location_gis_add.LocationAdd.as_view(),
        name='location_gis-add'),
    url(r'^location_gis/(?P<id>[0-9]+)$',
        location_gis_detail.LocationDetail.as_view(),
        name='location_gis-detail'),
    url(r'^location_gis/edit/(?P<id>[0-9]+)$',
        location_gis_edit.LocationEdit.as_view(),
        name='location_gis-edit'),
    url(r'^location_gis/delete/(?P<id>[0-9]+)$',
        location_gis_delete.LocationDelete.as_view(),
        name='location_gis-delete'),
    url(r'^location_gis_collection$',
        location_gis_collection.LocationCollectionView.as_view(),
        name="location_gis-collection"),

    # Fonds
    url(r'^fond$', fond.FondView.as_view(),
        name="fond"),
    url(r'^institution/(?P<id_institution>[0-9]+)/fond/add$',
        fond_add.FondAdd.as_view(),
        name='fond-add'),
    url(r'^fond/(?P<id>[0-9]+)$',
        fond_detail.FondDetail.as_view(),
        name='fond-detail'),
    url(r'^fond/edit/(?P<id>[0-9]+)$',
        fond_edit.FondEdit.as_view(),
        name='fond-edit'),
    url(r'^fond/delete/(?P<id>[0-9]+)$',
        fond_delete.FondDelete.as_view(),
        name='fond-delete'),

    # Mission
    url(r'^mission$', mission.MissionView.as_view(),
        name="mission"),
    url(r'^institution/(?P<id_institution>[0-9]+)/fond/(?P<id_fond>[0-9]+)/mission/add$',  # noqa
        mission_add.MissionAdd.as_view(),
        name='mission-add'),
    url(r'^mission/(?P<id>[0-9]+)$',
        mission_detail.MissionDetail.as_view(),
        name='mission-detail'),
    url(r'^mission/edit/(?P<id>[0-9]+)$',
        mission_edit.MissionEdit.as_view(),
        name='mission-edit'),
    url(r'^mission/delete/(?P<id>[0-9]+)$',
        mission_delete.MissionDelete.as_view(),
        name='mission-delete'),

    # Collection/Enquetes
    url(r'^collection$', collection.CollectionView.as_view(),
        name="collection"),
    url(r'^institution/(?P<id_institution>[0-9]+)/fond/(?P<id_fond>[0-9]+)/mission/(?P<id_mission>[0-9]+)/collection/add$',  # noqa
        collection_add.CollectionAdd.as_view(),
        name='collection-add'),
    url(r'^collection/(?P<id>[0-9]+)$',
        collection_detail.CollectionDetail.as_view(),
        name='collection-detail'),
    url(r'^collection/edit/(?P<id>[0-9]+)$',
        collection_edit.CollectionEdit.as_view(),
        name='collection-edit'),
    url(r'^collection/delete/(?P<id>[0-9]+)$',
        collection_delete.CollectionDelete.as_view(),
        name='collection-delete'),

    # Items
    url(r'^item$', item.ItemView.as_view(),
        name="item"),
    url(r'^institution/(?P<id_institution>[0-9]+)/fond/(?P<id_fond>[0-9]+)/mission/(?P<id_mission>[0-9]+)/collection/(?P<id_collection>[0-9]+)/item/add$',  # noqa
        item_add.ItemAdd.as_view(),
        name='item-add'),
    url(r'^item/(?P<id>[0-9]+)$',
        item_detail.ItemDetail.as_view(),
        name='item-detail'),
    url(r'^item/edit/(?P<id>[0-9]+)$',
        item_edit.ItemEdit.as_view(),
        name='item-edit'),
    url(r'^item/delete/(?P<id>[0-9]+)$',
        item_delete.ItemDelete.as_view(),
        name='item-delete'),

    # Instruments
    url(r'^instrument$', instrument.InstrumentView.as_view(),
        name="instrument"),
    url(r'^instrument/add$',
     instrument_add.InstrumentAdd.as_view(),
     name='instrument-add'),
    url(r'^instrument/(?P<id>[0-9]+)$',
     instrument_detail.InstrumentDetail.as_view(),
     name='instrument-detail'),
    url(r'^instrument/edit/(?P<id>[0-9]+)$',
         instrument_edit.InstrumentEdit.as_view(),
         name='instrument-edit'),
    url(r'^instrument/delete/(?P<id>[0-9]+)$',
        instrument_delete.InstrumentDelete.as_view(),
        name='instrument-delete'),

    # Domain Song
    url(r'^domain_song$', domain_song.DomainSongView.as_view(),
        name="domain_song"),
    url(r'^domain_song/add$',
     domain_song_add.DomainSongAdd.as_view(),
     name='domain_song-add'),
    url(r'^domain_song/(?P<id>[0-9]+)$',
     domain_song_detail.DomainSongDetail.as_view(),
     name='domain_song-detail'),
    url(r'^domain_song/edit/(?P<id>[0-9]+)$',
         domain_song_edit.DomainSongEdit.as_view(),
         name='domain_song-edit'),
    url(r'^domain_song/delete/(?P<id>[0-9]+)$',
        domain_song_delete.DomainSongDelete.as_view(),
        name='domain_song-delete'),

    # Domain Music
    url(r'^domain_music$', domain_music.DomainMusicView.as_view(),
        name="domain_music"),
    url(r'^domain_music/add$',
     domain_music_add.DomainMusicAdd.as_view(),
     name='domain_music-add'),
    url(r'^domain_music/(?P<id>[0-9]+)$',
     domain_music_detail.DomainMusicDetail.as_view(),
     name='domain_music-detail'),
    url(r'^domain_music/edit/(?P<id>[0-9]+)$',
         domain_music_edit.DomainMusicEdit.as_view(),
         name='domain_music-edit'),
    url(r'^domain_music/delete/(?P<id>[0-9]+)$',
        domain_music_delete.DomainMusicDelete.as_view(),
        name='domain_music-delete'),

    # Domain Tale
    url(r'^domain_tale$', domain_tale.DomainTaleView.as_view(),
        name="domain_tale"),
    url(r'^domain_tale/add$',
     domain_tale_add.DomainTaleAdd.as_view(),
     name='domain_tale-add'),
    url(r'^domain_tale/(?P<id>[0-9]+)$',
     domain_tale_detail.DomainTaleDetail.as_view(),
     name='domain_tale-detail'),
    url(r'^domain_tale/edit/(?P<id>[0-9]+)$',
         domain_tale_edit.DomainTaleEdit.as_view(),
         name='domain_tale-edit'),
    url(r'^domain_tale/delete/(?P<id>[0-9]+)$',
        domain_tale_delete.DomainTaleDelete.as_view(),
        name='domain_tale-delete'),


    # Domain Vocal
    url(r'^domain_vocal$', domain_vocal.DomainVocalView.as_view(),
        name="domain_vocal"),
    url(r'^domain_vocal/add$',
     domain_vocal_add.DomainVocalAdd.as_view(),
     name='domain_vocal-add'),
    url(r'^domain_vocal/(?P<id>[0-9]+)$',
     domain_vocal_detail.DomainVocalDetail.as_view(),
     name='domain_vocal-detail'),
    url(r'^domain_vocal/edit/(?P<id>[0-9]+)$',
         domain_vocal_edit.DomainVocalEdit.as_view(),
         name='domain_vocal-edit'),
    url(r'^domain_vocal/delete/(?P<id>[0-9]+)$',
        domain_vocal_delete.DomainVocalDelete.as_view(),
        name='domain_vocal-delete'),

    # Dance
    url(r'^dance$', dance.DanceView.as_view(),
        name="dance"),
    url(r'^dance/add$',
     dance_add.DanceAdd.as_view(),
     name='dance-add'),
    url(r'^dance/(?P<id>[0-9]+)$',
     dance_detail.DanceDetail.as_view(),
     name='dance-detail'),
    url(r'^dance/edit/(?P<id>[0-9]+)$',
         dance_edit.DanceEdit.as_view(),
         name='dance-edit'),
    url(r'^dance/delete/(?P<id>[0-9]+)$',
        dance_delete.DanceDelete.as_view(),
        name='dance-delete'),

    # Musical Organization
    url(r'^musical_organization$',
        musical_organization.MusicalOrganizationView.as_view(),
        name="musical_organization"),
    url(r'^musical_organization/add$',
        musical_organization_add.MusicalOrganizationAdd.as_view(),
        name='musical_organization-add'),
    url(r'^musical_organization/(?P<id>[0-9]+)$',
        musical_organization_detail.MusicalOrganizationDetail.as_view(),
        name='musical_organization-detail'),
    url(r'^musical_organization/edit/(?P<id>[0-9]+)$',
         musical_organization_edit.MusicalOrganizationEdit.as_view(),
         name='musical_organization-edit'),
    url(r'^musical_organization/delete/(?P<id>[0-9]+)$',
        musical_organization_delete.MusicalOrganizationDelete.as_view(),
        name='musical_organization-delete'),

    # hornbostelsachs
    url(r'^hornbostelsachs$', hornbostelsachs.HornbostelsachsView.as_view(),
        name="hornbostelsachs"),
    url(r'^hornbostelsachs/add$',
     hornbostelsachs_add.HornbostelsachsAdd.as_view(),
     name='hornbostelsachs-add'),
    url(r'^hornbostelsachs/(?P<id>[0-9]+)$',
     hornbostelsachs_detail.HornbostelsachsDetail.as_view(),
     name='hornbostelsachs-detail'),
    url(r'^hornbostelsachs/edit/(?P<id>[0-9]+)$',
         hornbostelsachs_edit.HornbostelsachsEdit.as_view(),
         name='hornbostelsachs-edit'),
    url(r'^hornbostelsachs/delete/(?P<id>[0-9]+)$',
        hornbostelsachs_delete.HornbostelsachsDelete.as_view(),
        name='hornbostelsachs-delete'),

    # Emit vox
    url(r'^emit_vox$', emit_vox.EmitVoxView.as_view(),
        name="emit_vox"),
    url(r'^emit_vox/add$',
        emit_vox_add.EmitVoxAdd.as_view(),
        name='emit_vox-add'),
    url(r'^emit_vox/(?P<id>[0-9]+)$',
     emit_vox_detail.EmitVoxDetail.as_view(),
     name='emit_vox-detail'),
    url(r'^emit_vox/edit/(?P<id>[0-9]+)$',
         emit_vox_edit.EmitVoxEdit.as_view(),
         name='emit_vox-edit'),
    url(r'^emit_vox/delete/(?P<id>[0-9]+)$',
        emit_vox_delete.EmitVoxDelete.as_view(),
        name='emit_vox-delete'),

    # Language
    url(r'^language$', language.LanguageView.as_view(),
        name="language"),
    url(r'^language/add$',
        language_add.LanguageAdd.as_view(),
        name="language-add"),
    url(r'^language/(?P<id>[0-9]+)$',
        language_detail.LanguageDetail.as_view(),
        name="language-detail"),
    url(r'^language/edit/(?P<id>[0-9]+)$',
        language_edit.LanguageEdit.as_view(),
        name="language-edit"),
    url(r'^language/delete/(?P<id>[0-9]+)$',
        language_delete.LanguageDelete.as_view(),
        name="language-delete"),

    # thematic
    url(r'^thematic$', thematic.ThematicView.as_view(),
        name="thematic"),
    url(r'^thematic/add$',
        thematic_add.ThematicAdd.as_view(),
        name='thematic-add'),
    url(r'^thematic/(?P<id>[0-9]+)$',
     thematic_detail.ThematicDetail.as_view(),
     name='thematic-detail'),
    url(r'^thematic/edit/(?P<id>[0-9]+)$',
         thematic_edit.ThematicEdit.as_view(),
         name='thematic-edit'),
    url(r'^thematic/delete/(?P<id>[0-9]+)$',
        thematic_delete.ThematicDelete.as_view(),
        name='thematic-delete'),

    # Coirault
    url(r'^coirault/(?P<id>[0-9]+)$',
        coirault_detail.CoiraultDetail.as_view(),
        name='coirault-detail'),

    # Musical Group
    url(r'^musical_group$',
        musical_group.MusicalGroupView.as_view(),
        name="musical_group"),
    url(r'^musical_group/add$',
        musical_group_add.MusicalGroupAdd.as_view(),
        name='musical_group-add'),
    url(r'^musical_group/(?P<id>[0-9]+)$',
        musical_group_detail.MusicalGroupDetail.as_view(),
        name='musical_group-detail'),
    url(r'^musical_group/edit/(?P<id>[0-9]+)$',
         musical_group_edit.MusicalGroupEdit.as_view(),
         name='musical_group-edit'),
    url(r'^musical_group/delete/(?P<id>[0-9]+)$',
        musical_group_delete.MusicalGroupDelete.as_view(),
        name='musical_group-delete'),

    # usefulness
    url(r'^usefulness$', usefulness.UsefulnessView.as_view(),
        name="usefulness"),
    url(r'^usefulness/add$',
     usefulness_add.UsefulnessAdd.as_view(),
     name='usefulness-add'),
    url(r'^usefulness/(?P<id>[0-9]+)$',
     usefulness_detail.UsefulnessDetail.as_view(),
     name='usefulness-detail'),
    url(r'^usefulness/edit/(?P<id>[0-9]+)$',
         usefulness_edit.UsefulnessEdit.as_view(),
         name='usefulness-edit'),
    url(r'^usefulness/delete/(?P<id>[0-9]+)$',
        usefulness_delete.UsefulnessDelete.as_view(),
        name='usefulness-delete'),

    # Coupe
    url(r'^coupe$', coupe.CoupeView.as_view(),
        name="coupe"),
    url(r'^coupe/add$',
     coupe_add.CoupeAdd.as_view(),
     name='coupe-add'),
    url(r'^coupe/(?P<id>[0-9]+)$',
     coupe_detail.CoupeDetail.as_view(),
     name='coupe-detail'),
    url(r'^coupe/edit/(?P<id>[0-9]+)$',
         coupe_edit.CoupeEdit.as_view(),
         name='coupe-edit'),
    url(r'^coupe/delete/(?P<id>[0-9]+)$',
        coupe_delete.CoupeDelete.as_view(),
        name='coupe-delete'),

    # LegalRights
    url(r'^legal_rights$', legal_rights.LegalRightsView.as_view(),
        name="legal_rights"),
    url(r'^legal_rights/add$',
     legal_rights_add.LegalRightsAdd.as_view(),
     name='legal_rights-add'),
    url(r'^legal_rights/(?P<id>[0-9]+)$',
     legal_rights_detail.LegalRightsDetail.as_view(),
     name='legal_rights-detail'),
    url(r'^legal_rights/edit/(?P<id>[0-9]+)$',
         legal_rights_edit.LegalRightsEdit.as_view(),
         name='legal_rights-edit'),
    url(r'^legal_rights/delete/(?P<id>[0-9]+)$',
        legal_rights_delete.LegalRightsDelete.as_view(),
        name='legal_rights-delete'),


    # mediatype
    url(r'^mediatype$', mediatype.MediaTypeView.as_view(),
        name="mediatype"),
    url(r'^mediatype/add$',
     mediatype_add.MediaTypeAdd.as_view(),
     name='mediatype-add'),
    url(r'^mediatype/(?P<id>[0-9]+)$',
        mediatype_detail.MediaTypeDetail.as_view(),
        name='mediatype-detail'),
    url(r'^mediatype/edit/(?P<id>[0-9]+)$',
        mediatype_edit.MediaTypeEdit.as_view(),
        name='mediatype-edit'),
    url(r'^mediatype/delete/(?P<id>[0-9]+)$',
        mediatype_delete.MediaTypeDelete.as_view(),
        name='mediatype-delete'),

    # metadata_author
    url(r'^metadata_author$', metadata_author.MetadataAuthorView.as_view(),
        name="metadata_author"),
    url(r'^metadata_author/add$',
     metadata_author_add.MetadataAuthorAdd.as_view(),
     name='metadata_author-add'),
    url(r'^metadata_author/(?P<id>[0-9]+)$',
     metadata_author_detail.MetadataAuthorDetail.as_view(),
     name='metadata_author-detail'),
    url(r'^metadata_author/edit/(?P<id>[0-9]+)$',
         metadata_author_edit.MetadataAuthorEdit.as_view(),
         name='metadata_author-edit'),
    url(r'^metadata_author/delete/(?P<id>[0-9]+)$',
        metadata_author_delete.MetadataAuthorDelete.as_view(),
        name='metadata_author-delete'),

    # Publisher
    url(r'^publisher$', publisher.PublisherView.as_view(),
        name="publisher"),
    url(r'^publisher/add$',
     publisher_add.PublisherAdd.as_view(),
     name='publisher-add'),
    url(r'^publisher/(?P<id>[0-9]+)$',
        publisher_detail.PublisherDetail.as_view(),
        name='publisher-detail'),
    url(r'^publisher/edit/(?P<id>[0-9]+)$',
        publisher_edit.PublisherEdit.as_view(),
        name='publisher-edit'),
    url(r'^publisher/delete/(?P<id>[0-9]+)$',
        publisher_delete.PublisherDelete.as_view(),
        name='publisher-delete'),

    # Recording context
    url(r'^recording_context$', recording_context.RecordingContextView.
        as_view(),
        name="recording_context"),
    url(r'^recording_context/add$',
     recording_context_add.RecordingContextAdd.as_view(),
     name='recording_context-add'),
    url(r'^recording_context/(?P<id>[0-9]+)$',
        recording_context_detail.RecordingContextDetail.as_view(),
        name='recording_context-detail'),
    url(r'^recording_context/edit/(?P<id>[0-9]+)$',
        recording_context_edit.RecordingContextEdit.as_view(),
        name='recording_context-edit'),
    url(r'^recording_context/delete/(?P<id>[0-9]+)$',
        recording_context_delete.RecordingContextDelete.as_view(),
        name='recording_context-delete'),
]
