---

- name: 'INFRA | Prerequisites'
  hosts: 'all'
  tasks:
    - name: 'Install packages'
      package:
        name: "{{ item }}"
      loop: "{{ francoralite_system_packages }}"

    - name: 'Install PIP packages'
      pip:
        name: "{{ item }}"
      loop: "{{ francoralite_pip_packages }}"

    - name: 'INFRA | Deploy Docker networks'
      docker_network:
        name: "{{ item.name }}"
      loop: "{{ _docker_service_networks | default([]) }}"


- name: 'SERVICE | Deploy Francoralite using Ansistrano'
  hosts: 'all'
  environment:
    COMPOSE_PROJECT_NAME: 'francoralite'
  vars:
    ansistrano_deploy_to: "{{ _ansistrano_deploy_to }}"
    ansistrano_deploy_via: "{{ _ansistrano_deploy_via }}"
    ansistrano_git_repo: "{{ _ansistrano_git_repo }}"
    ansistrano_git_branch: "{{ _ansistrano_git_branch }}"
    ansistrano_keep_releases: "{{ _ansistrano_keep_releases }}"
  roles:
    - { role: 'ansistrano.deploy' }
  post_tasks:
    - name: 'Force Nginx restart'
      service:
        name: 'nginx'
        state: 'restarted'
