---

- name: 'Populate Keycloak clients'
  hosts: 'localhost'
  tasks:
    - name: 'KEYCLOAK | Manage Francoralite clients'
      become: False
      keycloak_client: "{{ _keycloak_client_base | combine(item) }}"
      delegate_to: 'keycloak.francoralite.localhost'
      loop: "{{ _keycloak_clients }}"
  vars_files:
    - './vars/keycloak_data.yml'
