name: CI Workflow
on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      
      - name : Create services network
        run: docker network create services
      
      - name: Retrieve docker images
        if: ${{ success() }}
        run: docker-compose pull
      
      - name: Build docker image
        if: ${{ success() }}
        run: docker-compose build
      
      - name: Start docker-compose
        if: ${{ success() }}
        run: docker-compose up --no-start
        
      - name: Keycloak parameters
        if: ${{ success() }}
        run: script -e -c "./scripts/load_keycloak_data.sh"
       
      - name: Install tests dependencies
        if: ${{ success() }}
        run: script -e -c "docker-compose exec app bash -c 'pip install --no-cache-dir .[tests]'"
        
      - name: Run backends tests
        if: ${{ success() }}
        run: script -e -c "docker-compose exec app bash -c 'py.test --cov coveralls --cov-report term-missing --cov=resources'"
      - name: Covert to lcov
        if: ${{ success() }}
        run: |
          coveragepy-lcov
        
      #- name: Coveralls
      #  if: ${{ success() }}
      #  run: script -e -c "docker-compose exec app bash -c 'coveralls --service=github'"
      #  env:
      #    COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Coveralls token
        if: ${{ success() }}
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: lcov.info
        
      - name: Logs docker-compose
        if: ${{ failure() }}
        run: docker-compose logs

      - name: Stop docker-compose
        if: ${{ always() }}
        run: docker-compose stop

      - name: Down docker-compose
        if: ${{ always() }}
        run: docker-compose down
