name: CI Workflow
on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name : Create services network
        run: docker network create services
      - name: Retrieve docker images
        run: docker-compose pull
      - name: Build docker image
        run: docker-compose build
      - name: Start docker-compose
        run: docker-compose up --no-start
