name: CI Workflow
on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve docker images
        run: docker-compose pull
      - name: Build docker image
        run: docker-compose build
